### ISSUE TITLE
Does not recognize dv.current()

### ISSUE THREAD

**Issue by trych** [udus122/dataview-publisher#51]
Hi there,

first of all, thanks for the great plugin!

I wish to output sibling pages of my current page and therefore try to access the current page programmatically.
And while the `dv.page()` and the `dv.pages()` method seem to get evaluated just fine, I am having trouble running the `dv.current()`.

The console always tells me

```
Uncaught (in promise) TypeError: dv.current is not a function
    at eval (eval at executeBlock (plugin:dataview-publisher:1:1), <anonymous>:2:24)
```

I am basically trying to do something like this:
```js
// Get all pages in current folder
let currentFolder = dv.current().file.folder;
let silbings = dv.pages(`"${currentFolder}"`).map(s =>`[[${s.file.name}]]`);
`
## Siblings

${dv.markdownList(siblings)}
`;
```
Why does this not work? Am I doing something wrong? Is there another way to reference the current page object?

Thanks!

**Comment by udus122** [comment]
Thank you for telling me.

That is because the JS execution function of dataview-publisher is implemented using `eval`.

What you want will be achieved by switching to a [Function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function)/[AsyncFunction](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction) based implementation and passing the `dv` object to those constructor as an argument.

I want to work on it, but I haven't been able to do it yet.

**Comment by udus122** [comment]
@trych That is because the `dv` object accessible within eval is [DataviewApi](https://github.com/blacksmithgu/obsidian-dataview/blob/6d9030ef1df9c3f310f42e3502149dc71792dc4d/src/api/plugin-api.ts#L77), not [DataviewInlineApi](https://github.com/blacksmithgu/obsidian-dataview/blob/6d9030ef1df9c3f310f42e3502149dc71792dc4d/src/api/inline-api.ts#L39C14-L39C31).

I don't know how to create a DataviewInlineApi from outside the Dataview Plugin.
If I knew how to do that, I might be able to use `dv.current()`.

I made it possible to access the [TFile](https://docs.obsidian.md/Reference/TypeScript+API/TFile) object of the current file using the name `file` within the eval function.

Therefore, you may be able to achieve what you want by doing the following.

After updating the plugin, Could you try updating the plugin and then give it a try?

```js
// let currentFolder = dv.current().file.folder;
let currentFolder = dv.page(file.path)
let siblings = dv.pages(`"${currentFolder.file.folder}"`).map(s =>`[[${s.file.name}]]`);
`
## Siblings
${dv.markdownList(siblings)}
`

**Comment by trych** [comment]
@udus122 Thanks for looking into this.

Unfortunately, when I try your code snippet, I am getting this:
![20241117-134132_Screenshot_Obsidian](https://github.com/user-attachments/assets/173ae62f-d9bd-4c11-9590-d1bd7d487075)

**Comment by udus122** [comment]
@trych The runtime of Dataview Plugin and dataview-publisher are different, and they do not share variables.

So, even if an error occurs when displaying dataview, the output of dataview-publisher should be displayed.

The runtime of Dataview Plugin and dataview-publisher are different, and they do not share variables.

Therefore, even if an error occurs when displaying dataview, the output of dataview-publisher should be displayed.

What happens when you run the command "Dataview Publisher: Update dataview. publish blocks"?

**Comment by trych** [comment]
@udus122 My apologies, you are right of course. I just copied your codeblock and totally forgot to insert it into the `%%DATAVIEW_PUBLISHER` setup and to publish it via command.

On my first testing attempts, it works now really well. Thanks a lot!
